"""initial schema

Revision ID: 93593f087541
Revises: 
Create Date: 2026-04-28 16:11:36.629528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93593f087541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_seen_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_seen', sa.DateTime(), nullable=True),
    sa.Column('date_sold', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trim', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drivetrain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('exterior_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interior_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seller_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accident_reported', sa.Boolean(), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.Column('cpo', sa.Boolean(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normalized_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expert_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comp_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('observed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_listing_id', sa.Uuid(), nullable=False),
    sa.Column('report_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_offer_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_offer_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sold_comp_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_comp_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('desirability_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seller_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comp_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('comp_listing_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comp_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comp_matches')
    op.drop_table('reports')
    op.drop_table('price_observations')
    op.drop_table('listings')
    # ### end Alembic commands ###
