"""add_email_capture_fields

Revision ID: e5a1a94886ed
Revises: c3e1d2a7f501
Create Date: 2026-05-04 20:02:56.244435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a1a94886ed'
down_revision: Union[str, Sequence[str], None] = 'c3e1d2a7f501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captures', sa.Column('name', sa.String(), nullable=True))
    op.add_column('email_captures', sa.Column('trim_interest', sa.String(), nullable=True))
    op.add_column('email_captures', sa.Column('budget_min', sa.Integer(), nullable=True))
    op.add_column('email_captures', sa.Column('budget_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_captures', 'budget_max')
    op.drop_column('email_captures', 'budget_min')
    op.drop_column('email_captures', 'trim_interest')
    op.drop_column('email_captures', 'name')
    # ### end Alembic commands ###
